site_name: Inferneo
site_description: Fast and efficient inference server for machine learning models
site_author: Inferneo Team
site_url: https://docs.inferneo.ai

repo_name: inferneo/inferneo
repo_url: https://github.com/inferneo/inferneo
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.delay
    - navigation.instant.loading
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/inferneo/inferneo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/inferneo_ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/inferneo

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home:
    - index.md
    - getting-started.md
    - installation.md
  - User Guide:
    - user-guide/quickstart.md
    - user-guide/offline-inference.md
    - user-guide/online-serving.md
    - user-guide/model-loading.md
    - user-guide/batching.md
    - user-guide/streaming.md
    - user-guide/quantization.md
    - user-guide/distributed-inference.md
  - Examples:
    - examples/text-generation.md
    - examples/chat-completion.md
    - examples/embeddings.md
    - examples/vision-models.md
    - examples/multimodal.md
  - API Reference:
    - api-reference/python-client.md
    - api-reference/rest-api.md
    - api-reference/websocket-api.md
    - api-reference/configuration.md
  - CLI Reference:
    - cli-reference/commands.md
    - cli-reference/environment-variables.md
  - Developer Guide:
    - developer-guide/architecture.md
    - developer-guide/contributing.md
    - developer-guide/custom-models.md
    - developer-guide/performance-tuning.md
  - Community:
    - community/roadmap.md
    - community/releases.md
    - community/faq.md

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - minify:
      minify_html: true 